baseurl = "/"
title = "Home"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "nwrana"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Author]
    name = "Nathan Wrana"
    #profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Data::Information"
    description = "communicating statistical learning and data visualizations in R and Python"
    github = "https://github.com/nwrana"
    #gitlab = "https://gitlab.com/xxx"
    linkedin = "https://linkedin.com/in/nwrana/"
    #gplus = "https://google.com/+XXX"
    #twitter = "https://twitter.com/XXX"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "nathan.wrana@gmail.com"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4